# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PJM\PycharmProjects\kodos\modules\kodosBAx.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName("gridlayout")
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        spacerItem = QtWidgets.QSpacerItem(70, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.textLabel1 = QtWidgets.QLabel(self.groupBox)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self._2.addWidget(self.textLabel1)
        self.matchNumberSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.matchNumberSpinBox.setMinimum(1)
        self.matchNumberSpinBox.setMaximum(9999)
        self.matchNumberSpinBox.setObjectName("matchNumberSpinBox")
        self._2.addWidget(self.matchNumberSpinBox)
        self.spacerLabel = QtWidgets.QLabel(self.groupBox)
        self.spacerLabel.setPixmap(QtGui.QPixmap("image1"))
        self.spacerLabel.setWordWrap(False)
        self.spacerLabel.setObjectName("spacerLabel")
        self._2.addWidget(self.spacerLabel)
        self.replaceLabel = QtWidgets.QLabel(self.groupBox)
        self.replaceLabel.setWordWrap(False)
        self.replaceLabel.setObjectName("replaceLabel")
        self._2.addWidget(self.replaceLabel)
        self.replaceNumberSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.replaceNumberSpinBox.setObjectName("replaceNumberSpinBox")
        self._2.addWidget(self.replaceNumberSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(118, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem1)
        self.gridlayout.addLayout(self._2, 5, 0, 1, 1)
        self.tabWidget3 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget3.setObjectName("tabWidget3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self._3 = QtWidgets.QGridLayout(self.tab)
        self._3.setObjectName("_3")
        self.stringMultiLineEdit = QtWidgets.QTextEdit(self.tab)
        self.stringMultiLineEdit.setObjectName("stringMultiLineEdit")
        self._3.addWidget(self.stringMultiLineEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self._4 = QtWidgets.QGridLayout(self.tab_2)
        self._4.setObjectName("_4")
        self.replaceTextEdit = QtWidgets.QTextEdit(self.tab_2)
        self.replaceTextEdit.setObjectName("replaceTextEdit")
        self._4.addWidget(self.replaceTextEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab_2, "")
        self.gridlayout.addWidget(self.tabWidget3, 4, 0, 1, 1)
        self.resultTabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.resultTabWidget.setObjectName("resultTabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self._5 = QtWidgets.QGridLayout(self.tab_3)
        self._5.setObjectName("_5")
        self.groupTable = QtWidgets.QTableWidget(self.tab_3)
        self.groupTable.setObjectName("groupTable")
        self.groupTable.setColumnCount(0)
        self.groupTable.setRowCount(0)
        self._5.addWidget(self.groupTable, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self._6 = QtWidgets.QGridLayout(self.tab_4)
        self._6.setObjectName("_6")
        self.matchTextBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.matchTextBrowser.setObjectName("matchTextBrowser")
        self._6.addWidget(self.matchTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.tab_4, "")
        self.TabPage = QtWidgets.QWidget()
        self.TabPage.setObjectName("TabPage")
        self._7 = QtWidgets.QGridLayout(self.TabPage)
        self._7.setObjectName("_7")
        self.matchAllTextBrowser = QtWidgets.QTextBrowser(self.TabPage)
        self.matchAllTextBrowser.setObjectName("matchAllTextBrowser")
        self._7.addWidget(self.matchAllTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage, "")
        self.TabPage_2 = QtWidgets.QWidget()
        self.TabPage_2.setObjectName("TabPage_2")
        self._8 = QtWidgets.QVBoxLayout(self.TabPage_2)
        self._8.setObjectName("_8")
        self.replaceTextBrowser = QtWidgets.QTextBrowser(self.TabPage_2)
        self.replaceTextBrowser.setObjectName("replaceTextBrowser")
        self._8.addWidget(self.replaceTextBrowser)
        self.resultTabWidget.addTab(self.TabPage_2, "")
        self.TabPage_3 = QtWidgets.QWidget()
        self.TabPage_3.setObjectName("TabPage_3")
        self._9 = QtWidgets.QGridLayout(self.TabPage_3)
        self._9.setObjectName("_9")
        self.codeTextBrowser = QtWidgets.QTextBrowser(self.TabPage_3)
        self.codeTextBrowser.setObjectName("codeTextBrowser")
        self._9.addWidget(self.codeTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage_3, "")
        self.gridlayout.addWidget(self.resultTabWidget, 6, 0, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName("groupBox1")
        self._10 = QtWidgets.QGridLayout(self.groupBox1)
        self._10.setObjectName("_10")
        self.regexMultiLineEdit = QtWidgets.QTextEdit(self.groupBox1)
        self.regexMultiLineEdit.setObjectName("regexMultiLineEdit")
        self._10.addWidget(self.regexMultiLineEdit, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.buttonGroup2 = QtWidgets.QGroupBox(self.groupBox)
        self.buttonGroup2.setObjectName("buttonGroup2")
        self._11 = QtWidgets.QHBoxLayout(self.buttonGroup2)
        self._11.setObjectName("_11")
        self.ignorecaseCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.ignorecaseCheckBox.setObjectName("ignorecaseCheckBox")
        self._11.addWidget(self.ignorecaseCheckBox)
        self.multilineCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.multilineCheckBox.setObjectName("multilineCheckBox")
        self._11.addWidget(self.multilineCheckBox)
        self.dotallCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.dotallCheckBox.setObjectName("dotallCheckBox")
        self._11.addWidget(self.dotallCheckBox)
        self.verboseCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.verboseCheckBox.setObjectName("verboseCheckBox")
        self._11.addWidget(self.verboseCheckBox)
        self.localeCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.localeCheckBox.setObjectName("localeCheckBox")
        self._11.addWidget(self.localeCheckBox)
        self.unicodeCheckBox = QtWidgets.QCheckBox(self.buttonGroup2)
        self.unicodeCheckBox.setObjectName("unicodeCheckBox")
        self._11.addWidget(self.unicodeCheckBox)
        self.gridlayout.addWidget(self.buttonGroup2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textLabel1.setText(_translate("MainWindow", "Match Number"))
        self.replaceLabel.setText(_translate("MainWindow", "Replace Number"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab), _translate("MainWindow", "Search String"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab_2), _translate("MainWindow", "Replace String"))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab_3), _translate("MainWindow", "Group"))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab_4), _translate("MainWindow", "Match"))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage), _translate("MainWindow", "Match All"))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage_2), _translate("MainWindow", "Replace"))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage_3), _translate("MainWindow", "Sample Code"))
        self.groupBox1.setTitle(_translate("MainWindow", "Regular Expresssion Pattern"))
        self.buttonGroup2.setTitle(_translate("MainWindow", "Flags"))
        self.ignorecaseCheckBox.setToolTip(_translate("MainWindow", "Perform case-insensitive matching; expressions like [A-Z] will match\n"
"lowercase letters, too. This is not affected by the current locale."))
        self.ignorecaseCheckBox.setText(_translate("MainWindow", "Ignore Case"))
        self.multilineCheckBox.setToolTip(_translate("MainWindow", "When specified, the pattern character \"^\" matches at the beginning of the \n"
"string and at the beginning of each line (immediately following each newline); \n"
"and the pattern character \"$\" matches at the end of the string and at the end \n"
"of each line (immediately preceding each newline). By default, \"^\" matches \n"
"only at the beginning of the string, and \"$\" only at the end of the string and \n"
"immediately before the newline (if any) at the end of the string."))
        self.multilineCheckBox.setText(_translate("MainWindow", "Multi Line"))
        self.dotallCheckBox.setToolTip(_translate("MainWindow", "Make the \".\" special character match any character at all, including a \n"
"newline; without this flag, \".\" will match anything except a newline."))
        self.dotallCheckBox.setText(_translate("MainWindow", "Dot All"))
        self.verboseCheckBox.setToolTip(_translate("MainWindow", "This flag allows you to write regular expressions that look nicer. Whitespace \n"
"within the pattern is ignored, except when in a character class or preceded by \n"
"an unescaped backslash, and, when a line contains a \"#\" neither in a character\n"
"class or preceded by an unescaped backslash, all characters from the leftmost \n"
"such \"#\" through the end of the line are ignored."))
        self.verboseCheckBox.setText(_translate("MainWindow", "Verbose"))
        self.localeCheckBox.setToolTip(_translate("MainWindow", "Make \\w, \\W, \\b, and \\B dependent on the current locale."))
        self.localeCheckBox.setText(_translate("MainWindow", "Locale"))
        self.unicodeCheckBox.setToolTip(_translate("MainWindow", "\"Make \\w, \\W, \\b, and \\B dependent on the Unicode character properties \n"
"database. New in Python version 2.0."))
        self.unicodeCheckBox.setText(_translate("MainWindow", "Unicode"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

