# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PJM\PycharmProjects\kodos\modules\prefsBA.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PrefsBA(object):
    def setupUi(self, PrefsBA):
        PrefsBA.setObjectName("PrefsBA")
        PrefsBA.resize(540, 257)
        PrefsBA.setSizeGripEnabled(False)
        self.layout5 = QtWidgets.QWidget(PrefsBA)
        self.layout5.setGeometry(QtCore.QRect(11, 6, 519, 246))
        self.layout5.setObjectName("layout5")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.layout5)
        self.vboxlayout.setContentsMargins(11, 11, 11, 11)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.TextLabel2 = QtWidgets.QLabel(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2.sizePolicy().hasHeightForWidth())
        self.TextLabel2.setSizePolicy(sizePolicy)
        self.TextLabel2.setWordWrap(False)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridlayout.addWidget(self.TextLabel2, 1, 0, 1, 1)
        self.browserButton = QtWidgets.QPushButton(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browserButton.sizePolicy().hasHeightForWidth())
        self.browserButton.setSizePolicy(sizePolicy)
        self.browserButton.setObjectName("browserButton")
        self.gridlayout.addWidget(self.browserButton, 0, 3, 1, 1)
        self.browserEdit = QtWidgets.QLineEdit(self.layout5)
        self.browserEdit.setObjectName("browserEdit")
        self.gridlayout.addWidget(self.browserEdit, 0, 1, 1, 2)
        self.fontButtonMatch = QtWidgets.QPushButton(self.layout5)
        self.fontButtonMatch.setText("")
        self.fontButtonMatch.setObjectName("fontButtonMatch")
        self.gridlayout.addWidget(self.fontButtonMatch, 2, 1, 2, 3)
        self.textLabel1 = QtWidgets.QLabel(self.layout5)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 2, 0, 1, 1)
        self.fontButton = QtWidgets.QPushButton(self.layout5)
        self.fontButton.setText("")
        self.fontButton.setObjectName("fontButton")
        self.gridlayout.addWidget(self.fontButton, 1, 1, 1, 3)
        self.emailServerEdit = QtWidgets.QLineEdit(self.layout5)
        self.emailServerEdit.setObjectName("emailServerEdit")
        self.gridlayout.addWidget(self.emailServerEdit, 4, 1, 1, 3)
        self.TextLabel1_2Emaii = QtWidgets.QLabel(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1_2Emaii.sizePolicy().hasHeightForWidth())
        self.TextLabel1_2Emaii.setSizePolicy(sizePolicy)
        self.TextLabel1_2Emaii.setWordWrap(False)
        self.TextLabel1_2Emaii.setObjectName("TextLabel1_2Emaii")
        self.gridlayout.addWidget(self.TextLabel1_2Emaii, 3, 0, 2, 1)
        self.TextLabel1_2 = QtWidgets.QLabel(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1_2.sizePolicy().hasHeightForWidth())
        self.TextLabel1_2.setSizePolicy(sizePolicy)
        self.TextLabel1_2.setWordWrap(False)
        self.TextLabel1_2.setObjectName("TextLabel1_2")
        self.gridlayout.addWidget(self.TextLabel1_2, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(380, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 5, 2, 1, 2)
        self.recentFilesSpinBox = QtWidgets.QSpinBox(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentFilesSpinBox.sizePolicy().hasHeightForWidth())
        self.recentFilesSpinBox.setSizePolicy(sizePolicy)
        self.recentFilesSpinBox.setMaximum(25)
        self.recentFilesSpinBox.setProperty("value", 5)
        self.recentFilesSpinBox.setObjectName("recentFilesSpinBox")
        self.gridlayout.addWidget(self.recentFilesSpinBox, 5, 1, 1, 1)
        self.TextLabel1 = QtWidgets.QLabel(self.layout5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1.sizePolicy().hasHeightForWidth())
        self.TextLabel1.setSizePolicy(sizePolicy)
        self.TextLabel1.setWordWrap(False)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridlayout.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.buttonHelp = QtWidgets.QPushButton(self.layout5)
        self.buttonHelp.setAutoDefault(True)
        self.buttonHelp.setObjectName("buttonHelp")
        self.hboxlayout.addWidget(self.buttonHelp)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.buttonApply = QtWidgets.QPushButton(self.layout5)
        self.buttonApply.setAutoDefault(True)
        self.buttonApply.setObjectName("buttonApply")
        self.hboxlayout.addWidget(self.buttonApply)
        self.buttonOk = QtWidgets.QPushButton(self.layout5)
        self.buttonOk.setAutoDefault(True)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.hboxlayout.addWidget(self.buttonOk)
        self.buttonCancel = QtWidgets.QPushButton(self.layout5)
        self.buttonCancel.setAutoDefault(True)
        self.buttonCancel.setObjectName("buttonCancel")
        self.hboxlayout.addWidget(self.buttonCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(PrefsBA)
        self.buttonOk.clicked.connect(PrefsBA.accept)
        self.buttonCancel.clicked.connect(PrefsBA.reject)
        self.browserButton.pressed.connect(PrefsBA.open)
        QtCore.QMetaObject.connectSlotsByName(PrefsBA)
        PrefsBA.setTabOrder(self.browserEdit, self.browserButton)
        PrefsBA.setTabOrder(self.browserButton, self.fontButton)
        PrefsBA.setTabOrder(self.fontButton, self.emailServerEdit)
        PrefsBA.setTabOrder(self.emailServerEdit, self.recentFilesSpinBox)
        PrefsBA.setTabOrder(self.recentFilesSpinBox, self.buttonHelp)
        PrefsBA.setTabOrder(self.buttonHelp, self.buttonApply)
        PrefsBA.setTabOrder(self.buttonApply, self.buttonOk)
        PrefsBA.setTabOrder(self.buttonOk, self.buttonCancel)

    def retranslateUi(self, PrefsBA):
        _translate = QtCore.QCoreApplication.translate
        PrefsBA.setWindowTitle(_translate("PrefsBA", "Preferences"))
        self.TextLabel2.setText(_translate("PrefsBA", "Editor Font:"))
        self.browserButton.setText(_translate("PrefsBA", "..."))
        self.textLabel1.setText(_translate("PrefsBA", "Match Font:"))
        self.TextLabel1_2Emaii.setText(_translate("PrefsBA", "Email Server:"))
        self.TextLabel1_2.setText(_translate("PrefsBA", "Recent Files:"))
        self.TextLabel1.setText(_translate("PrefsBA", "Web Browser:"))
        self.buttonHelp.setText(_translate("PrefsBA", "&Help"))
        self.buttonApply.setText(_translate("PrefsBA", "&Apply"))
        self.buttonOk.setText(_translate("PrefsBA", "&OK"))
        self.buttonCancel.setText(_translate("PrefsBA", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrefsBA = QtWidgets.QDialog()
    ui = Ui_PrefsBA()
    ui.setupUi(PrefsBA)
    PrefsBA.show()
    sys.exit(app.exec_())

