# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PJM\PycharmProjects\kodos\modules\regexLibraryBA.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegexLibraryBA(object):
    def setupUi(self, RegexLibraryBA):
        RegexLibraryBA.setObjectName("RegexLibraryBA")
        RegexLibraryBA.resize(491, 490)
        self.gridLayout = QtWidgets.QGridLayout(RegexLibraryBA)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.MenuBar = QtWidgets.QMenuBar(RegexLibraryBA)
        self.MenuBar.setObjectName("MenuBar")
        self.fileMenu = QtWidgets.QMenu(self.MenuBar)
        self.fileMenu.setObjectName("fileMenu")
        self.editMenu = QtWidgets.QMenu(self.MenuBar)
        self.editMenu.setObjectName("editMenu")
        self.helpMenu = QtWidgets.QMenu(self.MenuBar)
        self.helpMenu.setObjectName("helpMenu")
        self.gridLayout.addWidget(self.MenuBar, 0, 0, 1, 1)
        self.toolBar = Q3ToolBar(RegexLibraryBA)
        self.toolBar.setObjectName("toolBar")
        self.gridLayout.addWidget(self.toolBar, 1, 0, 1, 1)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.tabWidget3 = QtWidgets.QTabWidget(RegexLibraryBA)
        self.tabWidget3.setObjectName("tabWidget3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout1 = QtWidgets.QGridLayout(self.tab)
        self.gridlayout1.setContentsMargins(11, 11, 11, 11)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.regexTextBrowser = Q3TextBrowser(self.tab)
        self.regexTextBrowser.setObjectName("regexTextBrowser")
        self.gridlayout1.addWidget(self.regexTextBrowser, 0, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridlayout1.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridlayout2 = QtWidgets.QGridLayout(self.tab1)
        self.gridlayout2.setContentsMargins(11, 11, 11, 11)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.noteTextBrowser = Q3TextBrowser(self.tab1)
        self.noteTextBrowser.setObjectName("noteTextBrowser")
        self.gridlayout2.addWidget(self.noteTextBrowser, 1, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.textLabel3 = QtWidgets.QLabel(self.tab1)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.hboxlayout.addWidget(self.textLabel3)
        self.contribEdit = QtWidgets.QLineEdit(self.tab1)
        self.contribEdit.setReadOnly(True)
        self.contribEdit.setObjectName("contribEdit")
        self.hboxlayout.addWidget(self.contribEdit)
        self.gridlayout2.addLayout(self.hboxlayout, 2, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab1)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridlayout2.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab1, "")
        self.gridlayout.addWidget(self.tabWidget3, 1, 0, 1, 1)
        self.groupBox5 = QtWidgets.QGroupBox(RegexLibraryBA)
        self.groupBox5.setObjectName("groupBox5")
        self.gridlayout3 = QtWidgets.QGridLayout(self.groupBox5)
        self.gridlayout3.setContentsMargins(11, 11, 11, 11)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.descriptionListBox = Q3ListBox(self.groupBox5)
        self.descriptionListBox.setObjectName("descriptionListBox")
        self.gridlayout3.addWidget(self.descriptionListBox, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox5, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridlayout, 2, 0, 1, 1)
        self.editPasteAction = QtWidgets.QAction(RegexLibraryBA)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image1"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPasteAction.setIcon(icon)
        self.editPasteAction.setProperty("name", "editPasteAction")
        self.editPasteAction.setObjectName("editPasteAction")
        self.helpHelpAction = QtWidgets.QAction(RegexLibraryBA)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image2"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpHelpAction.setIcon(icon1)
        self.helpHelpAction.setProperty("name", "helpHelpAction")
        self.helpHelpAction.setObjectName("helpHelpAction")
        self.exitAction = QtWidgets.QAction(RegexLibraryBA)
        self.exitAction.setProperty("name", "exitAction")
        self.exitAction.setObjectName("exitAction")
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exitAction)
        self.editMenu.addAction(self.editPasteAction)
        self.editMenu.addSeparator()
        self.helpMenu.addAction(self.helpHelpAction)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.editMenu.menuAction())
        self.MenuBar.addAction(self.helpMenu.menuAction())
        self.toolBar.addAction(self.editPasteAction)

        self.retranslateUi(RegexLibraryBA)
        self.tabWidget3.setCurrentIndex(0)
        self.editPasteAction.activated.connect(RegexLibraryBA.editPaste)
        self.exitAction.activated.connect(RegexLibraryBA.close)
        QtCore.QMetaObject.connectSlotsByName(RegexLibraryBA)

    def retranslateUi(self, RegexLibraryBA):
        _translate = QtCore.QCoreApplication.translate
        RegexLibraryBA.setWindowTitle(_translate("RegexLibraryBA", "Kodos - Regex Library"))
        self.fileMenu.setTitle(_translate("RegexLibraryBA", "&File"))
        self.editMenu.setTitle(_translate("RegexLibraryBA", "&Edit"))
        self.helpMenu.setTitle(_translate("RegexLibraryBA", "&Help"))
        self.toolBar.setProperty("label", _translate("RegexLibraryBA", "Tools"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab), _translate("RegexLibraryBA", "Regex"))
        self.textLabel3.setText(_translate("RegexLibraryBA", "Contributed By:"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab1), _translate("RegexLibraryBA", "Notes"))
        self.groupBox5.setTitle(_translate("RegexLibraryBA", "Description"))
        self.editPasteAction.setText(_translate("RegexLibraryBA", "&Paste Example Into Kodos"))
        self.editPasteAction.setIconText(_translate("RegexLibraryBA", "Paste"))
        self.editPasteAction.setToolTip(_translate("RegexLibraryBA", "Paste This Example Into Kodos"))
        self.editPasteAction.setShortcut(_translate("RegexLibraryBA", "Ctrl+V"))
        self.helpHelpAction.setText(_translate("RegexLibraryBA", "&Help"))
        self.helpHelpAction.setIconText(_translate("RegexLibraryBA", "Help"))
        self.helpHelpAction.setShortcut(_translate("RegexLibraryBA", "Ctrl+/"))
        self.exitAction.setText(_translate("RegexLibraryBA", "&Exit"))
        self.exitAction.setIconText(_translate("RegexLibraryBA", "Exit"))

from q3listbox import Q3ListBox
from q3mainwindow import Q3MainWindow
from q3textbrowser import Q3TextBrowser
from q3toolbar import Q3ToolBar

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegexLibraryBA = QtWidgets.Q3MainWindow()
    ui = Ui_RegexLibraryBA()
    ui.setupUi(RegexLibraryBA)
    RegexLibraryBA.show()
    sys.exit(app.exec_())

