# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PJM\PycharmProjects\kodos\modules\referenceBA.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReferenceBA(object):
    def setupUi(self, ReferenceBA):
        ReferenceBA.setObjectName("ReferenceBA")
        ReferenceBA.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ReferenceBA)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setRowCount(32)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(29, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 1, item)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(17)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        ReferenceBA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReferenceBA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ReferenceBA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReferenceBA)
        self.statusbar.setObjectName("statusbar")
        ReferenceBA.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(ReferenceBA)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(ReferenceBA)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(ReferenceBA)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(ReferenceBA)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtWidgets.QAction(ReferenceBA)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(ReferenceBA)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ReferenceBA)
        QtCore.QMetaObject.connectSlotsByName(ReferenceBA)

    def retranslateUi(self, ReferenceBA):
        _translate = QtCore.QCoreApplication.translate
        ReferenceBA.setWindowTitle(_translate("ReferenceBA", "Kodos - Regex Reference Guide"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ReferenceBA", "Symbol"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ReferenceBA", "Definition"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("ReferenceBA", "."))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("ReferenceBA", "Matches any character"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("ReferenceBA", "*"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("ReferenceBA", "Matches 0 or more repetition of preceeding RE"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("ReferenceBA", "+"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("ReferenceBA", "Matches 1 or more repetition of preceeding RE"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("ReferenceBA", "?"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("ReferenceBA", "Matches 0 or 1 repetition of preceeding RE"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("ReferenceBA", "^"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("ReferenceBA", "Matches start of string"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("ReferenceBA", "$"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("ReferenceBA", "Matches the end of the string"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("ReferenceBA", "\\A"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("ReferenceBA", "Matches only at the start of the string"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("ReferenceBA", "\\B"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("ReferenceBA", "Matches the empty string, but only when it is not at the beginning or end of a  word"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("ReferenceBA", "\\b"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("ReferenceBA", "Matches the empty string, but only at the beginning or end of a word"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("ReferenceBA", "\\d"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("ReferenceBA", "Matches any decimal digit"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("ReferenceBA", "\\D"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("ReferenceBA", "Matches any non-digit character"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("ReferenceBA", "\\z"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("ReferenceBA", "Matches only at the end of the string"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("ReferenceBA", "\\W"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("ReferenceBA", "Matches any non-word"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("ReferenceBA", "\\w"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("ReferenceBA", "Matches any word"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("ReferenceBA", "\\S"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("ReferenceBA", "Matches any non-whitespace character"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("ReferenceBA", "\\s"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("ReferenceBA", "Matches any whitespace character"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("ReferenceBA", "\\\\"))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("ReferenceBA", "Matches a literal backslash"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("ReferenceBA", "??"))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("ReferenceBA", "Non-greedy ?"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("ReferenceBA", "*?"))
        item = self.tableWidget.item(18, 1)
        item.setText(_translate("ReferenceBA", "Non-greedy *"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("ReferenceBA", "+?"))
        item = self.tableWidget.item(19, 1)
        item.setText(_translate("ReferenceBA", "Non-greedy +"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("ReferenceBA", "()"))
        item = self.tableWidget.item(20, 1)
        item.setText(_translate("ReferenceBA", "Capturing Parenthesis"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("ReferenceBA", "(?:)"))
        item = self.tableWidget.item(21, 1)
        item.setText(_translate("ReferenceBA", "Non-capturing Parenthesis"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("ReferenceBA", "[]"))
        item = self.tableWidget.item(22, 1)
        item.setText(_translate("ReferenceBA", "Character class"))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("ReferenceBA", "{m,n}"))
        item = self.tableWidget.item(23, 1)
        item.setText(_translate("ReferenceBA", "match from m to n repetitions of the preceding RE, attempting to match as many repetitions as possible. "))
        item = self.tableWidget.item(24, 0)
        item.setText(_translate("ReferenceBA", "{m,n}?"))
        item = self.tableWidget.item(24, 1)
        item.setText(_translate("ReferenceBA", "match from m to n repetitions of the preceding RE, attempting to match as few repetitions as possible. "))
        item = self.tableWidget.item(25, 0)
        item.setText(_translate("ReferenceBA", "(?P<name>...)"))
        item = self.tableWidget.item(25, 1)
        item.setText(_translate("ReferenceBA", "Similar to regular parentheses, but the substring matched by the group is accessible via the symbolic group name name."))
        item = self.tableWidget.item(26, 0)
        item.setText(_translate("ReferenceBA", "(?P=name)"))
        item = self.tableWidget.item(26, 1)
        item.setText(_translate("ReferenceBA", "Matches whatever text was matched by the earlier group named name. "))
        item = self.tableWidget.item(27, 0)
        item.setText(_translate("ReferenceBA", "\\number "))
        item = self.tableWidget.item(27, 1)
        item.setText(_translate("ReferenceBA", "Matches the contents of the group of the same number. Groups are numbered starting from 1."))
        item = self.tableWidget.item(28, 0)
        item.setText(_translate("ReferenceBA", "(?<=...)"))
        item = self.tableWidget.item(28, 1)
        item.setText(_translate("ReferenceBA", "Matches if the current position in the string is preceded by a match for ... that ends at the current position. This is called a positive lookbehind assertion."))
        item = self.tableWidget.item(29, 0)
        item.setText(_translate("ReferenceBA", "(?<!...)"))
        item = self.tableWidget.item(29, 1)
        item.setText(_translate("ReferenceBA", "Matches if the current position in the string is not preceded by a match for .... This is called a negative lookbehind assertion."))
        item = self.tableWidget.item(30, 0)
        item.setText(_translate("ReferenceBA", "(?=...) "))
        item = self.tableWidget.item(30, 1)
        item.setText(_translate("ReferenceBA", "Matches if ... matches next, but doesn\'t consume any of the string. This is called a lookahead assertion."))
        item = self.tableWidget.item(31, 0)
        item.setText(_translate("ReferenceBA", "(?!...)"))
        item = self.tableWidget.item(31, 1)
        item.setText(_translate("ReferenceBA", "Matches if ... doesn\'t match next. This is a negative lookahead assertion"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("ReferenceBA", "File"))
        self.menuEdit.setTitle(_translate("ReferenceBA", "Edit"))
        self.menuHelp.setTitle(_translate("ReferenceBA", "Help"))
        self.actionNew.setText(_translate("ReferenceBA", "New"))
        self.actionOpen.setText(_translate("ReferenceBA", "Open"))
        self.actionSave.setText(_translate("ReferenceBA", "Save"))
        self.actionSaveAs.setText(_translate("ReferenceBA", "SaveAs"))
        self.actionPrint.setText(_translate("ReferenceBA", "Print"))
        self.actionExit.setText(_translate("ReferenceBA", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReferenceBA = QtWidgets.QMainWindow()
    ui = Ui_ReferenceBA()
    ui.setupUi(ReferenceBA)
    ReferenceBA.show()
    sys.exit(app.exec_())

