# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PJM\PycharmProjects\kodos\modules\reportBugBA.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_reportBugBA(object):
    def setupUi(self, reportBugBA):
        reportBugBA.setObjectName("reportBugBA")
        reportBugBA.resize(750, 653)
        self.gridlayout = QtWidgets.QGridLayout(reportBugBA)
        self.gridlayout.setContentsMargins(11, 11, 11, 11)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.submitButton = QtWidgets.QPushButton(reportBugBA)
        self.submitButton.setObjectName("submitButton")
        self.hboxlayout.addWidget(self.submitButton)
        self.cancelButton = QtWidgets.QPushButton(reportBugBA)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.gridlayout.addLayout(self.hboxlayout, 3, 0, 1, 1)
        self.GroupBox5 = QtWidgets.QGroupBox(reportBugBA)
        self.GroupBox5.setObjectName("GroupBox5")
        self.gridlayout1 = QtWidgets.QGridLayout(self.GroupBox5)
        self.gridlayout1.setContentsMargins(11, 11, 11, 11)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.TextLabel1 = QtWidgets.QLabel(self.GroupBox5)
        self.TextLabel1.setWordWrap(False)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridlayout1.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.TextLabel3 = QtWidgets.QLabel(self.GroupBox5)
        self.TextLabel3.setWordWrap(False)
        self.TextLabel3.setObjectName("TextLabel3")
        self.gridlayout1.addWidget(self.TextLabel3, 2, 0, 1, 1)
        self.TextLabel2 = QtWidgets.QLabel(self.GroupBox5)
        self.TextLabel2.setWordWrap(False)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridlayout1.addWidget(self.TextLabel2, 1, 0, 1, 1)
        self.OSEdit = QtWidgets.QLineEdit(self.GroupBox5)
        self.OSEdit.setObjectName("OSEdit")
        self.gridlayout1.addWidget(self.OSEdit, 0, 1, 1, 1)
        self.pythonVersionEdit = QtWidgets.QLineEdit(self.GroupBox5)
        self.pythonVersionEdit.setObjectName("pythonVersionEdit")
        self.gridlayout1.addWidget(self.pythonVersionEdit, 1, 1, 1, 1)
        self.PyQtVersionEdit = QtWidgets.QLineEdit(self.GroupBox5)
        self.PyQtVersionEdit.setObjectName("PyQtVersionEdit")
        self.gridlayout1.addWidget(self.PyQtVersionEdit, 2, 1, 1, 1)
        self.gridlayout.addWidget(self.GroupBox5, 0, 0, 1, 1)
        self.GroupBox6 = QtWidgets.QGroupBox(reportBugBA)
        self.GroupBox6.setObjectName("GroupBox6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GroupBox6)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.TextLabel4 = QtWidgets.QLabel(self.GroupBox6)
        self.TextLabel4.setWordWrap(False)
        self.TextLabel4.setObjectName("TextLabel4")
        self.vboxlayout.addWidget(self.TextLabel4)
        self.TextLabel5 = QtWidgets.QLabel(self.GroupBox6)
        self.TextLabel5.setWordWrap(False)
        self.TextLabel5.setObjectName("TextLabel5")
        self.vboxlayout.addWidget(self.TextLabel5)
        self.horizontalLayout.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.regexMultiLineEdit = Q3MultiLineEdit(self.GroupBox6)
        self.regexMultiLineEdit.setProperty("readOnly", True)
        self.regexMultiLineEdit.setObjectName("regexMultiLineEdit")
        self.vboxlayout1.addWidget(self.regexMultiLineEdit)
        self.stringMultiLineEdit = Q3MultiLineEdit(self.GroupBox6)
        self.stringMultiLineEdit.setProperty("readOnly", True)
        self.stringMultiLineEdit.setObjectName("stringMultiLineEdit")
        self.vboxlayout1.addWidget(self.stringMultiLineEdit)
        self.horizontalLayout.addLayout(self.vboxlayout1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridlayout.addWidget(self.GroupBox6, 1, 0, 1, 1)
        self.GroupBox7 = QtWidgets.QGroupBox(reportBugBA)
        self.GroupBox7.setObjectName("GroupBox7")
        self.gridlayout2 = QtWidgets.QGridLayout(self.GroupBox7)
        self.gridlayout2.setContentsMargins(11, 11, 11, 11)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.gridlayout3 = QtWidgets.QGridLayout()
        self.gridlayout3.setContentsMargins(0, 0, 0, 0)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.commentsMultiLineEdit = Q3MultiLineEdit(self.GroupBox7)
        self.commentsMultiLineEdit.setObjectName("commentsMultiLineEdit")
        self.gridlayout3.addWidget(self.commentsMultiLineEdit, 1, 1, 1, 1)
        self.TextLabel3_2 = QtWidgets.QLabel(self.GroupBox7)
        self.TextLabel3_2.setWordWrap(False)
        self.TextLabel3_2.setObjectName("TextLabel3_2")
        self.gridlayout3.addWidget(self.TextLabel3_2, 1, 0, 1, 1)
        self.emailAddressEdit = QtWidgets.QLineEdit(self.GroupBox7)
        self.emailAddressEdit.setObjectName("emailAddressEdit")
        self.gridlayout3.addWidget(self.emailAddressEdit, 0, 1, 1, 1)
        self.TextLabel2_2 = QtWidgets.QLabel(self.GroupBox7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2_2.sizePolicy().hasHeightForWidth())
        self.TextLabel2_2.setSizePolicy(sizePolicy)
        self.TextLabel2_2.setWordWrap(False)
        self.TextLabel2_2.setObjectName("TextLabel2_2")
        self.gridlayout3.addWidget(self.TextLabel2_2, 0, 0, 1, 1)
        self.gridlayout2.addLayout(self.gridlayout3, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.GroupBox7, 2, 0, 1, 1)

        self.retranslateUi(reportBugBA)
        self.submitButton.clicked.connect(reportBugBA.submit_slot)
        self.cancelButton.clicked.connect(reportBugBA.cancel_slot)
        QtCore.QMetaObject.connectSlotsByName(reportBugBA)
        reportBugBA.setTabOrder(self.OSEdit, self.pythonVersionEdit)
        reportBugBA.setTabOrder(self.pythonVersionEdit, self.PyQtVersionEdit)
        reportBugBA.setTabOrder(self.PyQtVersionEdit, self.emailAddressEdit)
        reportBugBA.setTabOrder(self.emailAddressEdit, self.commentsMultiLineEdit)
        reportBugBA.setTabOrder(self.commentsMultiLineEdit, self.submitButton)
        reportBugBA.setTabOrder(self.submitButton, self.cancelButton)
        reportBugBA.setTabOrder(self.cancelButton, self.regexMultiLineEdit)
        reportBugBA.setTabOrder(self.regexMultiLineEdit, self.stringMultiLineEdit)

    def retranslateUi(self, reportBugBA):
        _translate = QtCore.QCoreApplication.translate
        reportBugBA.setWindowTitle(_translate("reportBugBA", "Form1"))
        self.submitButton.setText(_translate("reportBugBA", "Submit Bug Report"))
        self.cancelButton.setText(_translate("reportBugBA", "Cancel"))
        self.GroupBox5.setTitle(_translate("reportBugBA", "System Information"))
        self.TextLabel1.setText(_translate("reportBugBA", "Operating System:"))
        self.TextLabel3.setText(_translate("reportBugBA", "PyQt Version:"))
        self.TextLabel2.setText(_translate("reportBugBA", "Python Version:"))
        self.GroupBox6.setTitle(_translate("reportBugBA", "Kodos State Information"))
        self.TextLabel4.setText(_translate("reportBugBA", "Regular Expression:"))
        self.TextLabel5.setText(_translate("reportBugBA", "Match String:"))
        self.GroupBox7.setTitle(_translate("reportBugBA", "Comments"))
        self.TextLabel3_2.setText(_translate("reportBugBA", "Comments:"))
        self.TextLabel2_2.setText(_translate("reportBugBA", "Email address:"))

from q3multilineedit import Q3MultiLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reportBugBA = QtWidgets.QWidget()
    ui = Ui_reportBugBA()
    ui.setupUi(reportBugBA)
    reportBugBA.show()
    sys.exit(app.exec_())

